# This is use for git configuration
name: Python Unit Tests

# which branch we are operating on
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
  # environment we are running on
    runs-on: ubuntu-latestn

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest tests
